import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import MoodContextProvider from '@/context/mood-context'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Bi-Polar Mood Switcher',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <MoodContextProvider>
          <Header />
          {children}
        </MoodContextProvider>
      </body>
    </html>
  )
}
